name: Update Pioneer
on:
  schedule:
    - cron: '0 0 * * *'  # Run daily
  workflow_dispatch:

jobs:
  update-pioneer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.15'

    - name: Add swap space
      run: |
        sudo fallocate -l 8G /swapfile
        sudo chmod 600 /swapfile
        sudo mkswap /swapfile
        sudo swapon /swapfile
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        mkdir processed_data

    - name: Clone MTGODecklistCache and AtomicCards.json
      run: |
        cd ../
        git clone https://github.com/brossignol/MTGODecklistCache --depth 1
        curl https://mtgjson.com/api/v5/AtomicCards.json > AtomicCards.json
        cd -
        
    - name: Process data
      run: |
        echo "running process_data.py Pioneer"
        python process_data.py Pioneer
        echo "zipping"
        zip Pioneer.zip processed_data/*
        rm processed_data/*

    - name: Commit files
      run: |
        git pull
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -a -m "Add changes Pioneer $(date)"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}